chore(tags): add macosarmjava tag
PrismLauncher/refraction pull request #226
Opened 2023-08-15 22:44 UTC by Lutitious

Add a tag to link to downloads for MacOS arm Java for azul

2023-08-15 23:19 UTC, TayouVR commented on tags/macosarmjava.md
> +- [Java 8](https://aka.ms/vs/17/release/vc_redist.x64.exe) for versions ≤ 1.16
👀

2023-08-15 23:25 UTC, Lutitious commented on tags/macosarmjava.md
> +- [Java 8](https://aka.ms/vs/17/release/vc_redist.x64.exe) for versions ≤ 1.16
Oops

2023-08-16 02:50 UTC, ryanccn requested changes

2023-08-16 02:50 UTC, ryanccn commented on tags/macosarmjava.md
> +On MacOS Arm, also known as Apple Silicon (M1, M2, etc.), you will need to install The Arm Version of Java. We recommend using Azul, the links for which can be found below:
```suggestion
On macOS arm64, also known as Apple Silicon (M1, M2, etc.), you will need to install the arm64 version of Java. We recommend using builds from Azul, the links for which can be found below:
```

2023-08-16 02:50 UTC, ryanccn commented on tags/macosarmjava.md
> +It is recommended to install both Java 8 and Java 17
```suggestion
It is recommended to install both Java 8 and Java 17.
```

2023-08-16 02:50 UTC, ryanccn commented on tags/macosarmjava.md
> +title: Install Arm Java on MacOS
```suggestion
title: Install arm64 Java on macOS
```

2023-08-16 04:23 UTC, ryanccn approved these changes

2023-08-16 04:23 UTC, merged

2023-08-16 05:25 UTC, Scrumplex commented
Why wasn't this part of the Java tag?

2023-08-16 14:40 UTC, Lutitious commented
> Why wasn't this part of the Java tag?

I didn't think of that tbh