Better ping command
PrismLauncher/refraction pull request #327
Opened 2024-04-30 23:02 UTC by TheKodeToad

2024-04-30 23:28 UTC, getchoo requested changes

2024-04-30 23:28 UTC, getchoo commented on src/commands/general/ping.rs
> +
```suggestion
```

2024-04-30 23:28 UTC, getchoo commented on src/commands/general/ping.rs
> +const PING_PREFIX: &str = "<:catstareback:1078622789885497414> Pong!";
```suggestion
```

2024-04-30 23:28 UTC, getchoo commented on src/commands/general/ping.rs
> +
this is how it was implemented before. i don't see many cases where this is extremely useful in the first place, let alone RTT as well; so i don't see a reason to "improve" on the previous implementation either
```suggestion
  let resp = format!("Pong! (`{}ms`)", ctx.ping().await.as_millis());
  ctx.say(resp).await?;
```

2024-05-01 00:07 UTC, TheKodeToad commented
This is what most bots have so i don't see why not?

2024-05-01 08:47 UTC, Scrumplex approved these changes
IMO this is good

2024-05-01 08:47 UTC, merged