Add more common issues to look for in logs
PrismLauncher/refraction pull request #363
Opened 2024-07-15 18:23 UTC by maskersss

feel free to give feedback on the wording, i didn't really think too much about it so it can likely be improved

2024-08-01 13:12 UTC, TheKodeToad requested changes
Is there any reason you used backticks around certain text? Doesn't that just make it a little harder to read?

Anyway, thank you for the contribution!

2024-08-01 13:12 UTC, TheKodeToad commented on src/handlers/event/analyze_logs/issues.rs
> +				format!("Your installed version is {log_version}, while the newest version is {latest_version}.\nPlease update by pressing the `Update` button in Prism.")
```suggestion
				format!("Your installed version is {log_version}, while the newest version is {latest_version}.\nPlease update by pressing the `Update` button in the launcher or using your package manager.")
```

2024-08-01 13:12 UTC, TheKodeToad commented on src/handlers/event/analyze_logs/issues.rs
> +		To fix this, try doing `Edit > Version > Download All` and then launching your instance again."
```suggestion
		"You seem to be missing libraries. This is usually caused by launching offline before they can be downloaded.
		To fix this, first ensure you are connected to the internet. Then, try selecting `Edit > Version > Download All` and launching your instance again."
```

2024-08-01 13:12 UTC, TheKodeToad commented on src/handlers/event/analyze_logs/issues.rs
> +		"Fabric Rendering API".to_string(),
```suggestion
		"Missing Indium".to_string(),
```

2024-08-01 13:12 UTC, TheKodeToad commented on src/handlers/event/analyze_logs/issues.rs
> +		Please select the right version in `Edit > Version`."
```suggestion
		Please select Change Version while it is selected in `Edit > Version`."
```

2024-08-01 13:56 UTC, maskersss commented
i feel like backticks help separate just the regular text from exact button names you should press / an exact java argument / whatever, idk i don't really feel like they make the text harder to read

2024-08-01 14:00 UTC, maskersss commented
yeah looking at existing tags they usually explain what to click with more text rather than using backticks and just giving a list of buttons to press:
> To fix this, update forge to the latest version via the Versions tab
> (right click on Forge, click Change Version, and choose the latest one)

rather than

> `Edit > Version > Forge > Change Version > choose the latest one`

, if you want i can rewrite everything in the same style ig

2024-08-01 14:01 UTC, maskersss commented on src/handlers/event/analyze_logs/issues.rs
> +		Please select the right version in `Edit > Version`."
would make sense to add backticks around `Change Version` if we're keeping backticks

2024-08-01 17:13 UTC, TheKodeToad commented
Since the text is not monospace in the UI I think quotes would be better but that's still quite weird?

2024-08-01 17:26 UTC, maskersss commented
> Since the text is not monospace in the UI
wait huh

2024-08-01 17:29 UTC, maskersss commented
![image](https://github.com/user-attachments/assets/5187df37-a263-489a-a9db-3e31dac47742)
does the `Edit > Version` not look like this to you?

2024-08-01 17:56 UTC, TheKodeToad commented
> wait huh? if it's not and it just keeps them as characters then yeah that's not what i intended at all but i was sure backticks just make the text monospace?

The text in the launcher's UI is not monospace, I would personally use them only for something which appears in the logs

2024-08-01 18:15 UTC, maskersss commented
ah, i see

2024-08-01 18:26 UTC, maskersss commented
removed backticks for everything launcher button related, kept them for java args / refraction tags since thats how it was before

2024-08-01 18:40 UTC, TheKodeToad approved these changes

2024-08-04 11:12 UTC, getchoo requested changes

2024-08-04 11:12 UTC, getchoo commented on src/handlers/event/analyze_logs/issues.rs
> +			);
```suggestion
		let issue = if log_version_parts[0] < 8 {
			(
				"Outdated Prism Launcher".to_string(),
				format!("Your installed version is {log_version}, while the newest version is {latest_version}.\nPlease update; for more info see https://prismlauncher.org/download/")
			)
```

2024-08-04 11:12 UTC, getchoo commented on src/handlers/event/analyze_logs/issues.rs
> +		}
```suggestion
		} else {
			(
				"Outdated Prism Launcher".to_string(),
				format!("Your installed version is {log_version}, while the newest version is {latest_version}.\nPlease update by pressing the `Update` button in the launcher or using your package manager.")
			)
		};
		
        Ok(Some(issue))
```

2024-08-07 04:13 UTC, getchoo approved these changes

2024-08-08 00:09 UTC, merged